"""Lightweight RAG evaluation metrics.

Implements approximations of the RAGAS metrics described in the course lecture
(Conf_9-RAG.pdf) without requiring an external LLM-as-judge or the ragas library:

- **faithfulness** (fidelidad al contexto): Jaccard overlap between answer tokens
  and context tokens.  Bidirectional — measures vocabulary overlap.
- **groundedness** (anclaje): fraction of answer *sentences* that have lexical
  support in at least one context document.  Unidirectional from the answer —
  measures whether each claim can be attributed to the context rather than invented.
- **context_relevance**: mean retriever score of the context documents.

These are intentionally cheap approximations, suitable for automated regression
testing and quick quality checks during development.  They should be complemented
with human evaluation for the final defense.
"""

from __future__ import annotations

import re

from core.models import Query, RetrievedDocument

# Minimum fraction of a sentence's tokens that must appear in the context
# for the sentence to be considered "supported".
_SUPPORT_THRESHOLD = 0.30


class RAGEvaluator:
    """Computes lightweight faithfulness, groundedness and context relevance.

    Example:
        evaluator = RAGEvaluator()
        metrics = evaluator.evaluate(query, answer_text, retrieved_docs)
        print(metrics)
        # {'faithfulness': 0.72, 'groundedness': 0.80, 'context_relevance': 0.61}
    """

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def evaluate(
        self,
        query: Query,
        answer: str,
        context_docs: list[RetrievedDocument],
    ) -> dict[str, float]:
        """Compute all available metrics for one query-answer-context triplet.

        Args:
            query: Original user query.
            answer: Text generated by the RAG system.
            context_docs: Documents used as context for generation.

        Returns:
            Dict with keys ``faithfulness``, ``groundedness``, and
            ``context_relevance``, all in [0, 1].
        """
        return {
            "faithfulness": self.faithfulness(answer, context_docs),
            "groundedness": self.groundedness(answer, context_docs),
            "context_relevance": self.context_relevance(context_docs),
        }

    def faithfulness(
        self,
        answer: str,
        context_docs: list[RetrievedDocument],
    ) -> float:
        """Estimate what fraction of the answer vocabulary is grounded in the context.

        Computed as Jaccard similarity between the token sets of the answer
        and the combined token set of all context documents:

            faithfulness = |answer_tokens ∩ context_tokens| / |answer_tokens ∪ context_tokens|

        A value of 1.0 means every answer token appears somewhere in the context.
        A value of 0.0 means the answer shares no vocabulary with the context.

        Args:
            answer: Generated answer text.
            context_docs: Documents provided as context to the LLM.

        Returns:
            Jaccard overlap in [0, 1].  Returns 0.0 for empty inputs.
        """
        if not answer or not context_docs:
            return 0.0

        answer_tokens = self._tokenize(answer)
        context_tokens = self._context_token_set(context_docs)

        if not answer_tokens or not context_tokens:
            return 0.0

        intersection = answer_tokens & context_tokens
        union = answer_tokens | context_tokens
        return len(intersection) / len(union)

    def groundedness(
        self,
        answer: str,
        context_docs: list[RetrievedDocument],
    ) -> float:
        """Estimate what fraction of answer sentences are attributable to the context.

        Unlike faithfulness (which measures vocabulary overlap across the whole answer),
        groundedness works at the sentence level: each sentence is judged independently,
        and the score is the fraction of sentences that are "supported" — i.e. at least
        ``_SUPPORT_THRESHOLD`` (30%) of their content tokens appear in the context.

        This approximates the RAGAS groundedness metric: a high score means the LLM
        stayed within what the context provides; a low score suggests the LLM introduced
        information not present in the retrieved documents (potential hallucination).

        Args:
            answer: Generated answer text.
            context_docs: Documents provided as context to the LLM.

        Returns:
            Fraction of supported sentences in [0, 1].  Returns 0.0 for empty inputs.
        """
        if not answer or not context_docs:
            return 0.0

        sentences = self._split_sentences(answer)
        if not sentences:
            return 0.0

        context_tokens = self._context_token_set(context_docs)
        if not context_tokens:
            return 0.0

        supported = sum(
            1 for s in sentences if self._sentence_is_supported(s, context_tokens)
        )
        return supported / len(sentences)

    def context_relevance(
        self,
        context_docs: list[RetrievedDocument],
    ) -> float:
        """Estimate how relevant the context documents are to the query.

        Uses the retriever similarity scores already stored in each
        RetrievedDocument as a proxy for relevance.  Returns the mean score
        across all context documents.

        Args:
            context_docs: Documents with their retriever similarity scores.

        Returns:
            Mean relevance score in [0, 1].  Returns 0.0 for empty input.
        """
        if not context_docs:
            return 0.0
        return sum(doc.score for doc in context_docs) / len(context_docs)

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _sentence_is_supported(self, sentence: str, context_tokens: set[str]) -> bool:
        """Return True if enough of the sentence's tokens appear in the context."""
        tokens = self._tokenize(sentence)
        if not tokens:
            return False
        threshold = max(1, len(tokens) * _SUPPORT_THRESHOLD)
        return len(tokens & context_tokens) >= threshold

    @staticmethod
    def _split_sentences(text: str) -> list[str]:
        """Split text into sentences, keeping only those with ≥ 3 words."""
        raw = re.split(r"[.!?]+", text)
        return [s.strip() for s in raw if len(s.split()) >= 3]

    @staticmethod
    def _context_token_set(context_docs: list[RetrievedDocument]) -> set[str]:
        tokens: set[str] = set()
        for doc in context_docs:
            tokens.update(re.findall(r"\b[a-záéíóúüñ]{2,}\b", doc.document.text.lower()))
        return tokens

    @staticmethod
    def _tokenize(text: str) -> set[str]:
        """Lowercase word tokenizer that strips punctuation."""
        return set(re.findall(r"\b[a-záéíóúüñ]{2,}\b", text.lower()))
